apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-traefikgw
  namespace: gateway-api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-traefikgw
  template:
    metadata:
      labels:
        app: python-app-traefikgw
    spec:
      containers:
        - name: poc
          image: us-central1-docker.pkg.dev/playground-s-11-31f44a5d/my-repo/poc:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-traefikgw-service
  namespace: gateway-api-demo
spec:
  type: ClusterIP
  selector:
    app: python-app-traefikgw
  ports:
    - port: 80
      targetPort: 8000