apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
      - name: poc
        image: us-central1-docker.pkg.dev/playground-s-11-99ef194c/my-repo/poc:v1      
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ingress-nginx
spec:
  type: ClusterIP  # Hidden inside the cluster
  selector:
    app: ingress-nginx
  ports:
  - port: 80
    targetPort: 8000
