apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: haproxy-system
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    # Source: https://haproxy-ingress.github.io/docs/configuration/keys/#auth-tls-secret
    haproxy-ingress.github.io/auth-tls-secret: "haproxy-system/my-ca-secret"
    haproxy-ingress.github.io/auth-tls-verify-client: "on"
    
    # Source: https://haproxy-ingress.github.io/docs/configuration/keys/#config-backend
    haproxy-ingress.github.io/config-backend: |
      http-request set-header ssl-client-cert %[ssl_c_der,base64]
      http-request set-header x-proxy-id haproxy-ingress
      http-request set-header ssl-client-subject-dn CN=%[ssl_c_s_dn(cn)]
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - haproxy.34.72.8.234.nip.io
    secretName: haproxy-server-certs
  rules:
  - host: haproxy.34.72.8.234.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haproxy-service
            port:
              number: 80