# 3. Standard Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: traefik-ingress-demo
  annotations:
    kubernetes.io/ingress.class: "traefik-ingress"
    traefik.ingress.kubernetes.io/router.tls.options: "traefik-ingress-demo-traefik-mtls-policy@kubernetescrd"
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-ingress-demo-pass-client-cert@kubernetescrd"
spec:
  ingressClassName: traefik-ingress
  tls:
  - hosts:
    - traefik.34.42.98.217.nip.io
  rules:
  - host: traefik.34.42.98.217.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-service
            port:
              number: 80